const {sequelize, User, Course, Lesson,SubLesson, UserCourse, Order,Payment} = require('./models')
const bcrypt = require('bcryptjs');
const hashed = bcrypt.hashSync("1234")

sequelize
  .sync({ force: true })
  .then(() => {
    return User.bulkCreate([
      {
      firstName:"a",
    lastName: "a",
    address: "aa aa a aa a",

    password:hashed,

    email:"a@gmail.com",

    mobile:"0815565528",

    schoolName: "hogwort"}
    ]);
  })
  .then(() => {
    return Lesson.bulkCreate([
      {
        name: "บทที่ 1 การจำแนกสาร",
  description: "..",
  time: 10,
  price: 990,
color: ".."
},
      {
        name: "บทที่ 2 ธาตุและสารประกอบ",
  description: "..",
  time: 10,
  price: 990,
color: ".."
},
      {
        name: "บทที่ 3 สารละลายกรด-เบส",
  description: "..",
  time: 10,
  price: 990,
color: ".."
},
      {
        name: "บทที่ 4 การแยกสาร",
  description: "..",
  time: 10,
  price: 990,
color: ".."
},
      {
        name: "บทที่ 5 การเปลี่ยนแปลงของสาร",
  description: "..",
  time: 10,
  price: 990,
color: ".."
},
      {
        name: "บทที่ 1 ความปลอดภัยและทักษะในปฏิบัติการเคมี",
  description: "..",
  time: 10,
  price: 990,
color: ".."
},
      {
        name: "บทที่ 2 อะตอมและสมบัติของธาตุ",
  description: "..",
  time: 10,
  price: 990,
color: ".."
},
      {
        name: "บทที่ 3 พันธะเคมี",
  description: "..",
  time: 10,
  price: 990,
color: ".."
},
      {
        name: "บทที่ 4 โมลและสูตรเคมี",
  description: "..",
  time: 10,
  price: 990,
color: ".."
},
      {
        name: "บทที่ 5 สารละลาย",
  description: "..",
  time: 10,
  price: 990,
color: ".."
},
      {
        name: "บทที่ 6 ปริมาณสัมพันธ์",
  description: "..",
  time: 10,
  price: 990,
color: ".."
},
      {
        name: "บทที่ 7 แก๊สและสมบัติของแก๊ส",
  description: "..",
  time: 10,
  price: 990,
color: ".."
},
      {
        name: "บทที่ 8 อัตราการเกิดปฏิกิริยาเคมี",
  description: "..",
  time: 10,
  price: 990,
color: ".."
},
      {
        name: "บทที่ 9 สมดุลเคมี",
  description: "..",
  time: 10,
  price: 990,
color: ".."
},
      {
        name: "บทที่ 10 กรด-เบส",
  description: "..",
  time: 10,
  price: 990,
color: ".."
},
      {
        name: "บทที่ 11 เคมีไฟฟ้า",
  description: "..",
  time: 10,
  price: 990,
color: ".."
},
      {
        name: "บทที่ 12 เคมีอินทรีย์",
  description: "..",
  time: 10,
  price: 990,
color: ".."
},
      {
        name: "บทที่ 13 พอลิเมอร์",
  description: "..",
  time: 10,
  price: 990,
color: ".."
},


    ]);
  })
  .then(() => {
    return SubLesson.bulkCreate([
      
        {
          name: "การจำแนกสารรอบตัว",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สารละลาย",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สารบริสุทธิ์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การตรวจสอบสารละลายและสารบริสุทธิ์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ความเข้มข้นของสารละลาย",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "แบบจำลองอะตอม",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "เลขมวล เลขอะตอม และอนุภาคในอะตอม",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ไอโซโทป ไอโซโทน ไอโซบาร์ และไอโซอิเล็กทรอนิกส์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การจัดเรียงอิเล็กตรอนในอะตอม",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ตารางธาตุ",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ธาตุแทรนซิชัน",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สารประกอบ",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ชนิดของกรด-เบส และการเรียกชื่อกรด-เบส",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สมบัติของสารละลายกรด",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สารประสมบัติของสารละลายเบส",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การตรวจสอบความเป็นกรด-เบสของสารละลาย",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "เกลือ",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "pH ของสารละลาย",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การใช้อินดิเคเตอร์บอกความเป็นกรด-เบสของสารละลาย",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สารละลายกรดเบสในชีวิตประจำวันและในสิ่งมีชีวิต",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ผลของสภาพแวดล้อมต่อค่า pH ของสารละลาย",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การหยิบแยกออก การใช้แม่เหล็กดูด การกรอง การตกตะกอน",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การระเหย การตกผลึก การกลั่น การกลั่นด้วยไอน้ำ",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การสกัดด้วยตัวทำละลาย",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "โครมาโทกราฟี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การเปลี่ยนแปลงของสาร",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การถ่านโอนความร้อน",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การละลายของสาร",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ปฏิกิริยาเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "พลังงานกับการเกิดปฏิกิริยาเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ปฏิกิริยาเคมีในชีวิตประจำวัน",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "อัตราการเกิดปฏิกิริยาเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ความปลอดภัยในการทำงานกับสารเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "อุบัติเหตุจากสารเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การวัดปริมาณสาร",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "หน่วยวัด",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "วิธีการทางวิทยาศาสตร์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "แบบจำลองอะตอม",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "อนุภาคในอะตอมและไอโซโทป",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การจัดเรียงอิเล็กตรอนในอะตอม",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ารางธาตุและสมบัติของธาตุหมู่หลัก",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ธาตุแทรนซิชัน",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ธาตุกัมมันตรังสี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การนำธาตุไปใช้ประโยชน์และผลกระทบต่อสิ่งมีชีวิต",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สัญลักษณ์แบบจุดลิวอิสและกฎออกเตต",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "พันธะไอออนิก",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "พันธะโคเวเลนต์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "พันธะโลหะ",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การใช้ประโยชน์ของสารประกอบไอออนิก สารโคเวเลนต์ และโลหะ",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "โมลและสูตรเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สารละลาย",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ปริมาณสัมพันธ์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "มวลอะตอม",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "มวลโมเลกุล",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "โมล",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สูตรเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ความเข้มข้นของสารละลาย",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การเตรียมสารละลาย",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สมบัติบางประการของสารละลาย",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ปฏิกิริยาเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สมการเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การคำนวณปริมาณสารในปฏิกิริยาเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สารกำหนดปริมาณ",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ผลได้ร้อยละ",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "แก๊สและสมบัติของแก๊ส",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "อัตราการเกิดปฏิกิริยาเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สมดุลเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ความสัมพันธ์ระหว่างปริมาตร ความดัน อุณหภูมิ และจำนวนโมลของแก๊ส",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "กฎแก๊สอุดมคติ และความดันย่อย",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การประยุกต์ใช้ความรู้เกี่ยวกับแก๊สและสมบัติของแก๊ส",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ความหมายและการคำนวณอัตราการเกิดปฏิกิริยาเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "แนวคิดเกี่ยวกับอัตราการเกิดปฏิกิริยาเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ปัจจัยที่มีผลต่ออัตราการเกิดปฏิกิริยาเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: " ภาวะสมดุล",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ปัจจัยที่มีผลต่อสมดุล",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สมดุลเคมีในสิ่งมีชีวิต สิ่งแวดล้อม และอุตสาหกรรม",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "กรด-เบส",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "เคมีไฟฟ้า",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ทฤษฎีกรด-เบส",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ค่าคงที่สคู่กรด-เบส",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การแตกตัวของกรด เบส และน้ำ",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สมบัติกรด-เบสของเกลือ",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "pH ของสารละลายกรดและเบส",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การไทเทรตกรด-เบส",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สารละลายบัฟเฟอร์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การประยุกต์ใช้ความรู้เกี่ยวกับกรด-เบส",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "เลขออกซิเดชันและปฏิกิริยารีดอกซ์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การดุลสมการรีดอกซ์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "เซลล์ไฟฟ้าเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ประโยชน์ของเซลล์ไฟฟ้าเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "เทคโนโลยีเกี่ยวข้องกับเคมีไฟฟ้า",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "เคมีอินทรีย์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "พอลิเมอร์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "พันธะของคาร์บอนในสารประกอบอินทรีย์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สูตรโครงสร้างของสารประกอบอินทรีย์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "หมู่ฟังก์ชัน",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ชื่อของสารประกอบอินทรีย์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ไอโซเมอร์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สมบัติของสารประกอบอินทรีย์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "หมู่ฟัปฏิกิริยาของสารประกอบอินทรีย์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สารประกอบอินทรีย์ในชีวิตประจำวันและการนำไปใช้ประโยชน์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "พอลิเมอร์และมอนอเมอร์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ปฏิกิริยาการเกิดพอลิเมอร์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "โครงสร้างและสมบัติของพอลิเมอร์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การปรับปรุงสมบัติของพอลิเมอร์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ความปลอดภัยในการทำงานกับสารเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "อุบัติเหตุจากสารเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การวัดปริมาณสาร",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "หน่วยวัด",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "วิธีการทางวิทยาศาสตร์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "แบบจำลองอะตอม",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "อนุภาคในอะตอมและไอโซโทป",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การจัดเรียงอิเล็กตรอนในอะตอม",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ตารางธาตุและสมบัติของธาตุหมู่หลัก",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ความปลอดภัยในการทำงานกับสารเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ธาตุแทรนซิชัน",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ธาตุกัมมันตรังสี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การนำธาตุไปใช้ประโยชน์และผลกระทบต่อสิ่งมีชีวิต",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สัญลักษณ์แบบจุดลิวอิสและกฎออกเตต",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "พันธะไอออนิก",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "พันธะโคเวเลนต์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "พันธะโลหะ",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การใช้ประโยชน์ของสารประกอบไอออนิก สารโคเวเลนต์ และโลหะ",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "มวลอะตอม",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "มวลโมเลกุล",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "โมล",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สูตรเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ความเข้มข้นของสารละลาย",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การเตรียมสารละลาย",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สมบัติบางประการของสารละลาย",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ปฏิกิริยาเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สมการเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การคำนวณปริมาณสารในปฏิกิริยาเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สารกำหนดปริมาณ",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ผลได้ร้อยละ",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ความสัมพันธ์ระหว่างปริมาตร ความดัน อุณหภูมิ และจำนวนโมลของแก๊ส",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "กฎแก๊สอุดมคติ และความดันย่อย",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ทฤษฎีจลน์และการแพร่ของแก๊ส",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การประยุกต์ใช้ความรู้เกี่ยวกับแก๊สและสมบัติของแก๊ส",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ความหมายและการคำนวณอัตราการเกิดปฏิกิริยาเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "แนวคิดเกี่ยวกับอัตราการเกิดปฏิกิริยาเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ปัจจัยที่มีผลต่ออัตราการเกิดปฏิกิริยาเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ภาวะสมดุล",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ปัจจัยที่มีผลต่อสมดุล",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สมดุลเคมีในสิ่งมีชีวิต สิ่งแวดล้อม และอุตสาหกรรม",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ทฤษฎีกรด-เบส",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "คู่กรด-เบส",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การแตกตัวของกรด เบส และน้ำ",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สมบัติกรด-เบสของเกลือ",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "pH ของสารละลายกรดและเบส",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ปฏิกิริยาเคมีระหว่างกรดและเบส",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การไทเทรตกรด-เบส",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สารละลายบัฟเฟอร์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การประยุกต์ใช้ความรู้เกี่ยวกับกรด-เบส",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การดุลสมการรีดอกซ์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "เซลล์ไฟฟ้าเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ประโยชน์ของเซลล์ไฟฟ้าเคมี",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "เทคโนโลยีเกี่ยวข้องกับเคมีไฟฟ้า",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "พันธะของคาร์บอนในสารประกอบอินทรีย์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สูตรโครงสร้างของสารประกอบอินทรีย์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "หมู่ฟังก์ชัน",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ชื่อของสารประกอบอินทรีย์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ไอโซเมอร์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สมบัติของสารประกอบอินทรีย์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ปฏิกิริยาของสารประกอบอินทรีย์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "สารประกอบอินทรีย์ในชีวิตประจำวันและการนำไปใช้ประโยชน์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "พอลิเมอร์และมอนอเมอร์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "ปฏิกิริยาการเกิดพอลิเมอร์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "โครงสร้างและสมบัติของพอลิเมอร์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การปรับปรุงสมบัติของพอลิเมอร์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
        {
          name: "การแก้ปัญหาขยะจากพอลิเมอร์",
          description: "...",
          file: "...",
          video: "..",
          time: 6,
        },
    

    ]);
  })
  .then(() => {
    return Course.bulkCreate([
      {
        name: "เคมีม.ต้น",
        description: "วิชาเคมีระดับชั้น มัธยมต้น",
        price: 2900,
        timeMax: 44,
        courseImg: "src/assets/cardbg.jpg",
        color: "bg-[ffffff]",
      },
      {
        name: "เคมีม.4-1",
        description: "วิชาเคมีระดับชั้น มัธยม 4 เทอม 1",
        price: 2900,
        timeMax: 44,
        courseImg: "src/assets/cardbg.jpg",
        color: "bg-[ffffff]",
      },
      {
        name: "เคมีม.4-2",
        description: "วิชาเคมีระดับชั้น มัธยม 4 เทอม 2",
        price: 2900,
        timeMax: 44,
        courseImg: "src/assets/cardbg.jpg",
        color: "bg-[ffffff]",
      },
      {
        name: "เคมีม.5-1",
        description: "วิวิชาเคมีระดับชั้น มัธยม 5 เทอม 1",
        price: 2900,
        timeMax: 44,
        courseImg: "src/assets/cardbg.jpg",
        color: "bg-[ffffff]",
      },
      {
        name: "เคมีม.5-2",
        description: "วิชาเคมีระดับชั้น มัธยม 5 เทอม 2",
        price: 2900,
        timeMax: 44,
        courseImg: "src/assets/cardbg.jpg",
        color: "bg-[ffffff]",
      },
      {
        name: "เคมีม.6",
        description: "วิชาเคมีระดับชั้น มัธยม 6",
        price: 2900,
        timeMax: 44,
        courseImg: "src/assets/cardbg.jpg",
        color: "bg-[ffffff]",
      },
      {
        name: "เคมี A-Level",
        description: "วิชาเคมีระดับชั้น มัธยมต้น",
        price: 2900,
        timeMax: 44,
        courseImg: "src/assets/cardbg.jpg",
        color: "bg-[ffffff]",
      },

      
    ]);
  })
  .then(() => {
    return Order.bulkCreate([
      {
        quantity: 2,
        totalPrice: 1890,
        date: 2023-01-23,
      },

      
    ]);
  })
  .then(() => {
    return UserCourse.bulkCreate([
      {
        startDate: 2023-01-23,
        endDate: 2023-02-23,
        timeUse: 20,
        timeMax: 44,
        status: "paid",
      },

      
    ]);
  })
  .then(() => {
    return Payment.bulkCreate([
      {
        info: "...",
        status: "done",
        slipImg: "..url",
      },

      
    ]);
  })
  .then(()=>process.exit(0))
  .catch((err) => console.log(err.message));

